name: flutter_app
description: Gym Management System Phase 1 App
version: 1.0.0

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true